# Generated by Django 4.0.3 on 2022-04-10 16:09

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navertoon',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('day', models.TextField()),
                ('title', models.TextField()),
                ('thumbnail', models.TextField()),
                ('detail_link', models.TextField()),
                ('introduction', models.TextField()),
                ('writer', models.TextField()),
                ('genre', models.TextField()),
                ('age', models.TextField()),
            ],
        ),
    ]
