# Generated by Django 4.0.3 on 2022-05-26 05:10

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('counted', models.IntegerField()),
                ('last_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
